### ISSUE TITLE
Applying Front Matter Defaults to plugin-generated pages

### ISSUE THREAD

**Issue by ohadschn** [jekyll/jekyll-archives#107]
I couldn't get [Front Matter Defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults) to be applied on the plugin-generated category/tag pages, even when no filters were specified in the relevant `_config.yml` section:

```yaml
defaults:
  - scope:
      path: ""
    values:
      header:
        image: images/foo.jpg # this works for posts and pages, but not jekyll-archives pages
```

**Comment by piyushpaliwal** [comment]
This issue is open since a couple of years now. Is it possible to have some sort of configuration applied for adding the front matter defaults?

**Comment by ashmaroli** [comment]
@piyushpaliwal Have you tried changing the `type` value in the `defaults` configuration?
For example, say I want my *category archives* to default to `show_read_more: true`. The my config file would have the following:
```yaml
defaults:
  - scope:
      path: ""
      type: category  # For tag-based archive pages, this would have been 'tag'
    values:
      show_read_more: true
```
