### ISSUE TITLE
Archive template not found

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-archives#12]
With this config:

``` yaml
jekyll-archives:
  enabled:
    - year
  layouts:
    year: year-archive
  permalinks:
    year: '/:year/'
```

and a template called year-archive.html, I get this message on build:

``` bash
Build Warning: Layout 'archive' requested in /2008/ does not exist.
Build Warning: Layout 'archive' requested in /2009/ does not exist.
Build Warning: Layout 'archive' requested in /2010/ does not exist.
Build Warning: Layout 'archive' requested in /2011/ does not exist.
Build Warning: Layout 'archive' requested in /2012/ does not exist.
Build Warning: Layout 'archive' requested in /2013/ does not exist.
Build Warning: Layout 'archive' requested in /2014/ does not exist.
```

Additionally, any layout config settings are ignored if archive.html _does_ exist in the _layouts directory.
