### ISSUE TITLE
Create new placeholder

### ISSUE THREAD

**Issue by ddomdel** [jekyll/jekyll-archives#166]
Is it possible to create a new placeholder which "sees" the frontmatter of a post under a category?

Because, currently, I can only access the `:name` placeholder, as you can see below in the `permalinks`

My goal is to make the `/categories/` in the `/categories/:name` dynamic. In this case, accessing a frontmatter from a post.

```yaml
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```
