### ISSUE TITLE
No category archives generated

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-archives#22]
I was previously using the [example plugin on Jekyllrb.com](http://jekyllrb.com/docs/plugins/#generators) to generate my category archives.

I am trying to migrate to this plugin, but it is not creating _any_ archive pages for categories. (Date based archives work as expected.)

Here is the relevant part of my `_config.yml`

``` yml
jekyll-archives:
   layout: "archive_index"
   enabled:
      - year
      - month
      - category
   permalinks:
      year:     '/:year/'
      month:    '/:year/:month/'
      category: '/search/label/:name/'

gems:
   - jekyll-sass-converter
   - jekyll-archives
   - jekyll-sitemap
```

After I run `jekyll build`, the date based archive pages exist, but there is no `/search/` directory at all.
