### ISSUE TITLE
Archives only in local jekyll

### ISSUE THREAD

**Issue by leifniem** [jekyll/jekyll-archives#27]
Hi,

i have included this plugin in my jekyll site i'm building and it works fine locally. When i build it does in the given folder just fine.
But whenever i push the repo the permalinks for the archives do not work.
I Included it the following way and in the gemfile. Still no clue where i made a mistake.

```
jekyll-archives:
  enabled:
    - tags
    - categories
  layout: 'archives'
  permalinks:
    tag: '/:name/'
gems: 
  - jekyll-archives
```

Thanks in advance

Edit: http://leifs.website/ is the link. Just click on one of the tags below the post-title to  see the issue.
