### ISSUE TITLE
Can't get categories to work

### ISSUE THREAD

**Issue by mkess-ivy** [jekyll/jekyll-archives#39]
my _config.yml has:

```yaml
jekyll-archives:
  enabled: 
    - categories
  layout: 'category-archive' # /_layouts/category-archive.html
  permalinks: 
    category: '/category/:name/'

gems:
  - jekyll-sitemap
  - jekyll-archives
```

my category-archive.html layout file has:

```liquid
{% include header.html %}
<h1>Archive of posts with {{ page.type }} '{{ page.title }}'</h1>
<ul class="posts">
  {% for post in page.posts %}
    <li>
      <span class="post-date">{{ post.date | date: "%b %-d, %Y" }}</span>
      <a class="post-link" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
{% include analytics.html %}
{% include footer.html %}
```

for my food category, i created a food.html page:

```yaml
---
layout: category-archive
title: Food
permalink: /food/
---
```

this is the yaml for one of my blog posts:
```yaml
---
layout: post
title: Hello World!
categories: food
---
```

When I go to my siteurl/food - i see "Archive of posts with 'Food' but no posts.  I'm not sure what I did wrong.
