### ISSUE TITLE
Can’t output the content of {{ site.archives }}

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-archives#4]
Was experimenting with the as yet unreleased version of the plugin, but couldn’t get any values output from `{{ site.archives }}`. With the following config:

``` yaml
jekyll-archives:
  layout: archive
  permalinks:
    year: '/:name/'
    tag: '/tags/:name/'
    category: '/category/:name/'
```

and using this template:

``` html

---
layout: default

---
<section class="index section--archive">
    <header class="index__header">
        <p>{{ site.archives.type }}</p>
        <h1 class="index__title">{{ site.archives.name }}</h1>
    </header>

    <section class="section">
        {% for summary in site.archives.posts %}
        {% include articles/summary.html %}
        {% endfor %}
    </section>
</section>
```

Are these the correct values to be using?

(P.S. Thanks for taking on this project; the lack of proper archiving in Jekyll has been bugging me for a while!)
