### ISSUE TITLE
Double Tag Pages Generated

### ISSUE THREAD

**Issue by danielgroves** [jekyll/jekyll-archives#42]
I'm currently seeing duplicates of each tag page being generated. 

Configuration:

```
jekyll-archives:
  layouts: 
    tag: tag
  enabled:
    - tags
  permalinks:
    tag: tag/:name/
```

With this configuration I'd expect (given the tags: photography, backpacking):
* /tag/photography
* /tag/backpacking

What I'm actually seeing is:
* /photography
* /backpacking
* /tag/photography
* /tag/backpacking

I'm currently looking at this as being a bug, I can't see this being intended behaviour as once a URL as been set the default pages aren't required?  If this is intended it would at least be nice to see this as a configurable option?
