### ISSUE TITLE
Case sensitivity causes confusing archive generation

### ISSUE THREAD

**Issue by gboone** [jekyll/jekyll-archives#43]
The problem: You have both tags "USA" and "usa" and the following `jekyll-archives` configuration:
```
jekyll-archives:
  enabled:
    - 'tags'
  layout: tag_index
  permalinks:
    tag: '/tags/:name/'
```
USA has 4 posts
usa has 1 post

The result:
On the page generated at `/tags/usa` will include only the 4 posts tagged in caps.

Interim solution:
Users should build a habit of consistent tagging.
