### ISSUE TITLE
Archives do not generate with Jekyll 3.0.4

### ISSUE THREAD

**Issue by d4mation** [jekyll/jekyll-archives#61]
No Errors are apparent, unfortunately.

Reproduction Steps:
- Install latest version of Jekyll via `bundle` (Currently this is `3.0.4`)
- Install latest version of `jekyll-archives` (Currently `2.1.0`)
- Attempt `jekyll build` and no `index.html` files will be included were they should be

Workaround is rolling Jekyll back to `3.0`, but that prevents the `github-pages` Gem (And likely others) from installing as it specifies `3.0.4` currently.

Relevant section of my `_config.yml`:

```
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tag/:name/
    category: /category/:name/
    
gems:
  - jekyll-archives
  - jekyll-sitemap
```
