### ISSUE TITLE
`site.archives` template variable not available in archive layout

### ISSUE THREAD

**Issue by swashcap** [jekyll/jekyll-archives#62]
I’m attempting to create an archives list in a sidebar. The sidebar should appear on multiple pages, including the archive page itself. Unfortunately, the `site.archives` template variable doesn’t seem to be available in the archive-specified layout.

Here’s a basic example to reproduce:

_\_config.yml_:

```yaml
jekyll-archives
  enabled:
    - month
  layout: archive
  permalinks:
    month: "/archives/:year/:month/"
```

_\_layouts/archive.html_:

```html
---
layout: default
---

<h1>Archives</h1>
<ul>
  {% assign months = site.archives | where:"type", "month" %}
  {% for month in months %}
    <li>
      <a href="{{ month.url }}">{{ month.posts[0].date | date:"%b %Y" }}</a>
    </li>
  {% endfor %}
</ul>
```

* OS: **OS X 10.11.4**
* Ruby:  **2.3.0p0**
* jekyll: **3.0.5**
* jekyll-paginate: **1.1.0**
