### ISSUE TITLE
No Archive page generate

### ISSUE THREAD

**Issue by bbgky** [jekyll/jekyll-archives#66]
Hi, here is my repo: 
https://github.com/bbgky/bbgky.github.io
what i want is to generate archive pages. i did what the doc suggested:
 _1_. in the Gemfile, i did

```
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-paginate'
  gem 'jekyll-archives'
end
```

 _2_.  in the _config.yml i add

```
gems:
  - jekyll-archives

jekyll-archives:
      enabled: all
      layout: archive
      permalinks:
        year: /:year/
        month: /:year/:month/
        day: /:year/:month/:day/
        tag: /tag/:name/
        category: /category/:name/
```

I add a `archive.html` in the `_layouts` folder, with the code(copy paste from configuration.md):

```
<h1>Archive of posts from {{ page.date | date: "%B %Y" }}</h1>

<ul class="posts">
{% for post in page.posts %}
  <li>
    <span class="post-date">{{ post.date | date: "%b %-d, %Y" }}</span>
    <a class="post-link" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

```

I add a menu archive in the host with layout 'archive'. but it seems it is still not working?
It only shows 'Archive of posts from' without the files
![screenshot2](https://cloud.githubusercontent.com/assets/18110063/17757606/f1937e90-649c-11e6-9c5e-b2f8fd21538f.png)

What did i do wrong? and what am I missing to use jekyll-archives?

Thanks, I really appreciate your help
