### ISSUE TITLE
Error: superclass mismatch for class Archive

### ISSUE THREAD

**Issue by bradonomics** [jekyll/jekyll-archives#72]
I'm getting the error `jekyll 3.2.1 | Error:  superclass mismatch for class Archive` when running `jekyll build`. Here are the relevant files and configs:

### _config.yml

```
gems:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'
```

### Gemfile

```
source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-paginate'
  gem 'jekyll-archives'
end
```

### _plugins directory

```
_plugins/
├── jekyll-archives/
│   ├── archive.rb
│   └── version.rb
└── jekyll-archives.rb
```

### _layouts directory

```
_layouts/
└── archive.html
```

### archive.html file

```
---
layout: default
---

<h1>Archive of posts with {{ page.type }} '{{ page.title }}'</h1>
<ul class="posts">
  {% for post in page.posts %}
    <li>
      <span class="post-date">{{ post.date | date: "%b %-d, %Y" }}</span>
      <a class="post-link" href="{{ post.url | prepend: site.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
```

This is the first time I've tried to install a Jekyll plugin, so I'm not sure if all the above needs to have been done. I'm mostly guessing after having poked around the web.
