### ISSUE TITLE
Archive pages not being generated

### ISSUE THREAD

**Issue by claman** [jekyll/jekyll-archives#73]
I've followed the layout and config docs here in this repo, and as far as I can tell I've set everything up in correct way, but the individual archive pages, i.e. for each category, aren't being generated.

My `_config.yml`
````
gems:
  - jekyll-archives

# jekyll-archives settings
jekyll-archives:
  enabled:
    year
    month
    day
    categories
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    category: '/blog/category/:name/'`
````
All of the layouts exist
